---
# consul
consul_master_token: master
consul_server_hosts: "{{ groups['consul'] | map('extract', hostvars, 'ansible_host') | list }}"
consul_datacenter: dc1

# prometheus
prometheus_listen_port: 9090
prometheus_hosts: "{{ groups['prometheus'] | map('extract', hostvars, 'ansible_host') | list }}"
