---
- name: install grafana rpm
  yum:
    name: "{{ grafana_rpm_url }}"
    state: present
  become: yes

- name: put grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
  notify: restart grafana
  become: yes

- name: mkdir dashboards dir
  file:
    path: "{{ grafana_dashboards_dir }}"
    owner: grafana
    group: grafana
    mode: 0755
    state: directory
  become: yes

- name: put dashboard json
  copy:
    src: "{{ item }}"
    dest: "{{ grafana_dashboards_dir }}/{{ item }}"
    owner: grafana
    group: grafana
  with_items:
    - envoy-global.json
    - envoy-service-to-service.json
  become: yes
  notify: restart grafana

- name: be sure grafana started
  service:
    name: grafana-server
    state: started
    enabled: yes
  become: yes

- include: configure.yml
