---
- name: Put Go source
  template:
    src: app.go.j2
    dest: /var/app.go
  become: yes
  notify: restart app

- name: setup systemd
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart app

- name: starts app
  systemd:
    name: app.service
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
