---
protocol: HTTP
hosts:
  - name: myfront
    ingressAddr:
      host: 192.168.34.70
      port: 80
    substanceAddr:
      host: 127.0.0.1
      port: 8080
    egressHost: 0.0.0.0
dependentServices:
  - name: app
    egressPort: 9001

